name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2MwZmVhYWQtMWIxNi00YzQ3LTlmYTUtNWYxNjQ3MThjOTZlIiwidGVuYW50X2lkIjoiMWFiMzE4MWIwMjllZDZkYWUzMTAxMTU2OTgyN2VlMmM1M2U3N2RmNDMzOTcwNDNkNmJiOGQ0OWU4N2I4NDg5ZCIsImludGVybmFsX3NlY3JldCI6ImQ0NDgwZWI4LWUxNjctNDkzYS05MTg5LTEwNTc1MTMxNzkyNSJ9.2I1FqiGZDtUkjBNnof96CK08npC936rFK0DQSlS38ZQ"