import "../globals.css";
import { Providers } from "../providers";
import { Toaster } from "sonner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster richColors position="top-center" closeButton />
          {children}
        </Providers>
      </body>
    </html>
  );
}
