import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { Toaster } from "sonner";
import { NavBar } from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster richColors position="top-center" closeButton />
          <div className="h-screen">
            <div className="border-b shadow-sm h-[10vh]">
              <NavBar />
            </div>
            <div className="  h-[90vh]">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
